DirectoryPath: "C:/Users/Natasa.Kralj/Documents/docs/demo-test/public/docs/marks-portal"
EnforceHTTPS: true
FileExtension: .html
IgnoreURLs:
- "example.com"
IgnoreInternalURLs:
- "/misc/js/script.js"
- "/tabs.js"
IgnoreDirs:
- "lib"
- "/js"
CacheExpires: "20d"
CheckExternal: false
CheckMailto: false
CheckTel: false
IgnoreAltMissing: true
IgnoreDirectoryMissingTrailingSlash: true
EnforceHTTPS: false
DirectoryIndex: "index.html"