DirectoryPath: "C:/Users/Natasa.Kralj/Documents/docs/demo-test/public"
EnforceHTTPS: false
FileExtension: .html
IgnoreURLs:
- "example.com"
IgnoreInternalURLs:
- "/misc/js/script.js"
- "/js/"
IgnoreDirs:
- "lib"
- "/js"
CacheExpires: "20d"
CheckExternal: false
CheckMailto: false
CheckTel: false
IgnoreAltMissing: true
IgnoreDirectoryMissingTrailingSlash: true
DirectoryIndex: "index.html"
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true